#!/bin/sh
##===----------------------------------------------------------------------===##
##
## This source file is part of the Swift.org open source project
##
## Copyright (c) 2025 Apple Inc. and the Swift.org project authors
## Licensed under Apache License v2.0
##
## See LICENSE.txt for license information
## See CONTRIBUTORS.txt for the list of Swift.org project authors
##
## SPDX-License-Identifier: Apache-2.0
##
##===----------------------------------------------------------------------===##
set -eu
# Install script for Swiftly
# Usage: curl -fsSL https://swift.org/swiftly-install | sh

if ! command -v curl >/dev/null 2>&1 || ! command -v ps >/dev/null 2>&1 || ! command -v tar >/dev/null 2>&1 ; then
    echo "Missing one of more of the following programs: curl, ps, tar" >&2
    exit 1
fi

OS_NAME=$(uname -s)
OS_ARCH=$(uname -m)
TEMP_DIR=$(mktemp -d)

cd "${TEMP_DIR}"

case "$OS_NAME" in
    "Linux")
        curl -fsSLO "https://download.swift.org/swiftly/linux/swiftly-${OS_ARCH}.tar.gz"
        tar zxf "swiftly-${OS_ARCH}.tar.gz"
        ./swiftly init
        SWIFTLY_HOME_DIR=${SWIFTLY_HOME_DIR:-$HOME/.swiftly}
        ;;
    "Darwin")
        curl -fsSLO https://download.swift.org/swiftly/darwin/swiftly.pkg
        installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
        ~/.swiftly/bin/swiftly init
        SWIFTLY_HOME_DIR=${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}
        ;;
    *)
        echo "Unknown platform: $OS_NAME"
        echo "This script supports Linux and Darwin/macOS only"
        exit 1
        ;;
esac

echo "Swiftly installed! Run the following command to set up your environment:"
PARENT_SHELL=$(ps -o comm= -p "$PPID")
if [ "$PARENT_SHELL" = "fish" ]; then
    echo "source ${SWIFTLY_HOME_DIR}/env.fish"
else
    # Not fish: assume sh-compatible (bash/zsh)
    echo "source ${SWIFTLY_HOME_DIR}/env.sh"
fi

